name: 'deploy-to-ali-oss'
on:
  push:
    branches:
      - master

jobs:
  ali_oss_deploy:
    runs-on: ubuntu-latest
    name: Deploy Pages to Ali OSS
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # 使用 node:10
      - name: use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm install gulp -g
          npm run build
        env:
          CI: true


      - name: Deploy
        id: DeployOss
        uses: stevenzg/ali-oss-action@master
        with:
          region: 'oss-cn-beijing'
          accessKeyId: ${{ secrets.ACCESSKEY_ID }}
          accessKeySecret: ${{ secrets.ACCESSKEY_SECRET }}
          bucket: 'smartify-ui'
          bucketPath: '/lucklysheet/'
          filePath: 'dist'
      - name: Deploy Result
        run: echo "${{ steps.DeployOss.outputs.successCount }} success, ${{ steps.DeployOss.outputs.failCount }} fail."