name: deploy to aliyun oss

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 切代码到 runner
      - uses: actions/checkout@v1
        with:
          submodules: true
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm install gulp -g
          npm run build
        env:
          CI: true
      # 设置阿里云OSS的 id/secret，存储到 github 的 secrets 中
      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hangzhou
          access-key-id: ${{ secrets.ACCESSKEY_ID }}
          access-key-secret: ${{ secrets.ACCESSKEY_SECRET }}

      # 发布到阿里云OSS，
      - name: cp files to aliyun
        run: ossutil cp dist oss://smartify-ui/ -rf